# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientIP', models.GenericIPAddressField()),
                ('clientName', models.CharField(max_length=50)),
                ('clientcomment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trafficDownload', models.FloatField()),
                ('trafficUpload', models.FloatField()),
                ('trafficTime', models.DateField()),
                ('trafficIP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_for_client', to='traffic.Client')),
            ],
        ),
    ]
