# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientIP',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
